---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

    - name: print out the hostname of target
      command: hostname

    - name: Install Common packages
      apt:
        name:
          - libxml2-utils
          - make
          - gcc
          - bzip2
#         - Duo Pre-Requisites
          - libssl-dev
        state: latest
        update_cache: yes
  
    - name: Duo Key
      ansible.builtin.apt_key:
         url: http://apt-repo/repo-keys/duo.pgp
         state: present

    - name: Duo Repo
      ansible.builtin.apt_repository:
         repo: deb [arch=amd64] http://apt-repo/duo/ xenial main
         state: present
         filename: duorepo
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16.04'

    - name: Duo Repo
      ansible.builtin.apt_repository:
         repo: deb [arch=amd64] http://apt-repo/duo/ bionic main
         state: present
         filename: duorepo
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '18.04'

    - name: Duo Repo
      ansible.builtin.apt_repository:
         repo: deb [arch=amd64] http://apt-repo/duo/ focal main
         state: present
         filename: duorepo
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '20.04'

   - name: Duo Repo
      ansible.builtin.apt_repository:
         repo: deb [arch=amd64] http://apt-repo/duo/ jammy main
         state: present
         filename: duorepo
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22.04'


    - name: Duo Packages Install
      apt:
        name:
          - login-duo
        state: latest
        update_cache: yes

    - name: etc-security-login_duo.conf Update
      get_url:
        url: http://apt-repo/it-deploy/Duo/login_duo.conf
        dest: /etc/security/login_duo.conf
        mode: '0600'
        owner: root
        group: root
        backup: yes

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /etc/security/login_duo.conf
        owner: sshd
        group: root
        # mode: '0600'
    
    - name: Insert "DUO" configuration block into /etc/ssh/sshd_config
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
         ForceCommand /usr/sbin/login_duo
         PermitTunnel no
         AllowTcpForwarding no

